@echo off
cd /d "c:\Users\DELL\OneDrive\Desktop\PR"
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit: PR Event Registration Portal"
echo Setting remote...
git remote add origin https://github.com/sannidha-kmit/PREVENT
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.
